name: Deploy Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    paths:
    - 'docs/static/**.html'
    - '.github/workflows/deploy-pages.yml'
  workflow_dispatch:
    
concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  deploy:
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
        
    defaults:
      run:
        working-directory: docs

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - shell: bash
        run: |
          # * rename home to index
          mv static/0-—-home.html static/index.html
          find static/ -type f | xargs sed -i  's/0-—-home.html/index.html/g'

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/static

      - uses: actions/deploy-pages@v2
        id: deployment