name: Deploy Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    paths:
    - 'docs/static/**'
    - '.github/workflows/deploy-pages.yml'
  workflow_dispatch:
    
concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  deploy:
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
        
    defaults:
      run:
        working-directory: docs/static

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - shell: bash
        run: |
          # * rename home to index
          mv 0-—-home.html index.html
          find ./ -type f | xargs sed -i 's/0-—-home.html/index.html/g'
          
          # * remove serials from filename
          for f in *.html
          do
            mv -n $f $(echo $f | sed -e 's/^[0-9]\+-—-\([^\.]\+\)\.html/\1.html/g')
          done
          find ./ -type f | xargs sed -i 's/[0-9]\+-—-\([^\.]\+\)\.html/\1.html/g'

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/static

      - uses: actions/deploy-pages@v2
        id: deployment