name: Mirror Wiki

permissions:
  contents: write

on:
  push:
    paths:
    - 'docs/**.md'
    - '.github/workflows/mirror-wiki.yml'
    
concurrency:
  group: wiki
  cancel-in-progress: true

jobs:

  mirror-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs
          commit-message: "docs(wiki): mirror wiki (${{ github.sha }})"
          