name: Optimise SVG

permissions:
  contents: write

on:
  push:
    paths:
    - 'assets/**.svg'
  workflow_dispatch:

jobs:

  optimise-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ericcornelissen/svgo-action@v3
        id: svgo
        with:
          svgo-version: 3
          repo-token: ${{secrets.GITHUB_TOKEN}}
            
      - shell: bash
        run: |
          git status --porcelain | awk '/\.svg$/ {print $2}' | xargs -I {} sh -c 'cp {} $(basename {} .svg)-min.svg'
          
      - shell: bash
        run: |
          git reset --hard

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{steps.svgo.outputs.DID_OPTIMIZE}}
        with:
          commit_message: "chore(assets): :bento: optimise ${{steps.svgo.outputs.OPTIMIZED_COUNT}} svg(s)"
          commit_user_name: James
          commit_user_email: james@jamesnzl.xyz
          